### ISSUE TITLE
Weird light behaivour in engines? (could just be Godot 4.2.1 issue)

### ISSUE THREAD

**Issue by ZsoltHevesi** [AstrorEnales/blender_magicavoxel#10]
When trying to use this addon to create large maps, I noticed the lights cause some weird behaviour on meshes (in Godot, Blender does not have this issue with its lights). However, it only seems to be happening on the large MagicaVoxel models.
![Screenshot (396)](https://github.com/AstrorEnales/blender_magicavoxel/assets/124164938/ae7508a9-6c5d-4243-bb0d-3fcf5c53dee4)
![Screenshot (397)](https://github.com/AstrorEnales/blender_magicavoxel/assets/124164938/ffecfc30-27bd-4730-9fda-7ee638f1337e)

Both of these models where imported using Voxel size of 0.5, Greedy, and Material Per Colour, then exported to OBJ:
[magicaVox_files.zip](https://github.com/AstrorEnales/blender_magicavoxel/files/14474628/magicaVox_files.zip)

If anyone has used this addon and did something similar but on a different (or same) engine that didn't have this issue, please let me know and I'll create an issue for Godot instead.

**Comment by AstrorEnales** [comment]
Hi, i'm currently travelling so i will test it thoroughly end of march. But as all normal generation in the addon is the same for all settings this is likely a godot issue. But you can verify this quite easily by visualising the normals in blender for both models. If they look alright (facing outwards in the correct angle) after import in blender, something needs to be changed in godot settings

**Comment by ZsoltHevesi** [comment]
Yeah I'd be led to believe this is the case, but strangely, other voxel style meshes don't have this issue. Even if it's not an issue per se with the addon, it's definitely influencing something to do with the mesh, but I don't have enough experience in this field to find out what.

**Comment by AstrorEnales** [comment]
@ZsoltHevesi I tested this today and could reproduce the issue in Godot 4.2.1 and as i thought it's not an issue with the addon but rather with Godot.
However, i found what Godot is missing in order for the models to be lit correctly: UVs. When using for example "material per color" no UVs are generated during import and the obj in godot looks wrong. After doing a "UV unwrap in blender after import and then loading an obj into Godot, the model is lit correctly.
So i recommend doing a UV unwrap after import and before exporting the obj in blender.
I will still investigate whether there is an easy addition to the addon to have this work out of the box, rather than generating uv maps in every mode that usually wouldn't require it. If there is not, i will consider that instead.

**Comment by AstrorEnales** [comment]
Luckily there was an easy solution in just adding a UV layer during import (no real UVs needed) and the exported obj is lit correctly in Godot. Please test the latest release and let me know if it worked for you as well :)
https://github.com/AstrorEnales/blender_magicavoxel/releases/tag/v1.5.3
